
import type { Property } from './types';

export const PUNE_LOCALITIES: string[] = ["Kothrud", "Hinjewadi", "Hadapsar", "Baner", "Wakad", "Viman Nagar", "Koregaon Park", "Aundh"];

export const AMENITIES_LIST: string[] = ["Gym", "Parking", "Security", "Lift", "Balcony", "Swimming Pool", "Power Backup", "Vaastu Compliant", "Modular Kitchen"];

export const PROPERTIES: Property[] = [
  {
    id: 1,
    title: "Modern 2BHK Apartment in Hinjewadi",
    price: 7500000,
    location: "Hinjewadi",
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    type: '2BHK',
    isFeatured: true,
    description: "A spacious 2BHK perfect for a young family or IT professionals, located close to major IT hubs and essential amenities. Features a modern design with ample natural light.",
    amenities: ["Gym", "Parking", "Security", "Lift", "Swimming Pool", "Power Backup"],
    images: [
      "https://picsum.photos/seed/prop1img1/1200/800",
      "https://picsum.photos/seed/prop1img2/1200/800",
      "https://picsum.photos/seed/prop1img3/1200/800",
      "https://picsum.photos/seed/prop1img4/1200/800",
    ],
    floorPlanUrl: "https://picsum.photos/seed/prop1fp/800/600",
  },
  {
    id: 2,
    title: "Elegant 3BHK in Koregaon Park",
    price: 15000000,
    location: "Koregaon Park",
    bedrooms: 3,
    bathrooms: 3,
    area: 1800,
    type: '3BHK',
    isFeatured: true,
    description: "Experience luxury living in this premium 3BHK apartment located in Pune's most sought-after neighborhood. High-end finishes and world-class amenities.",
    amenities: ["Gym", "Parking", "Security", "Lift", "Balcony", "Swimming Pool", "Vaastu Compliant"],
    images: [
      "https://picsum.photos/seed/prop2img1/1200/800",
      "https://picsum.photos/seed/prop2img2/1200/800",
      "https://picsum.photos/seed/prop2img3/1200/800",
    ],
  },
  {
    id: 3,
    title: "Cozy 1BHK for First-Time Buyers in Kothrud",
    price: 5000000,
    location: "Kothrud",
    bedrooms: 1,
    bathrooms: 1,
    area: 650,
    type: '1BHK',
    isFeatured: false,
    description: "The perfect starter home. This charming 1BHK in the heart of Kothrud offers great connectivity and a friendly community atmosphere.",
    amenities: ["Parking", "Security", "Lift", "Balcony"],
    images: [
      "https://picsum.photos/seed/prop3img1/1200/800",
      "https://picsum.photos/seed/prop3img2/1200/800",
    ],
    floorPlanUrl: "https://picsum.photos/seed/prop3fp/800/600",
  },
  {
    id: 4,
    title: "Family-Friendly 3BHK in Baner",
    price: 12000000,
    location: "Baner",
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    type: '3BHK',
    isFeatured: true,
    description: "Spacious and well-ventilated 3BHK on Baner Road, ideal for families. Close to schools, hospitals, and shopping centers.",
    amenities: ["Gym", "Parking", "Security", "Lift", "Balcony", "Power Backup", "Modular Kitchen"],
    images: [
      "https://picsum.photos/seed/prop4img1/1200/800",
      "https://picsum.photos/seed/prop4img2/1200/800",
      "https://picsum.photos/seed/prop4img3/1200/800",
    ],
  },
  {
    id: 5,
    title: "Affordable 2BHK in Hadapsar",
    price: 6000000,
    location: "Hadapsar",
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    type: '2BHK',
    isFeatured: false,
    description: "A value-for-money 2BHK apartment with all essential amenities, providing excellent connectivity to Magarpatta and SP Infocity.",
    amenities: ["Parking", "Security", "Lift", "Power Backup"],
    images: [
      "https://picsum.photos/seed/prop5img1/1200/800",
      "https://picsum.photos/seed/prop5img2/1200/800",
    ],
  },
  {
    id: 6,
    title: "Compact 1BHK in Wakad",
    price: 4500000,
    location: "Wakad",
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    type: '1BHK',
    isFeatured: false,
    description: "Ideal for bachelors and young couples, this 1BHK in Wakad is a smart investment with high rental potential due to its proximity to the IT park.",
    amenities: ["Parking", "Security", "Lift", "Balcony"],
    images: [
        "https://picsum.photos/seed/prop6img1/1200/800",
    ],
    floorPlanUrl: "https://picsum.photos/seed/prop6fp/800/600",
  },
    {
    id: 7,
    title: "Spacious 4BHK+ Penthouse in Aundh",
    price: 25000000,
    location: "Aundh",
    bedrooms: 4,
    bathrooms: 4,
    area: 2500,
    type: '4BHK+',
    isFeatured: false,
    description: "A luxurious penthouse offering panoramic city views. Features a private terrace and premium interiors.",
    amenities: ["Gym", "Parking", "Security", "Lift", "Balcony", "Swimming Pool", "Power Backup", "Modular Kitchen"],
    images: [
      "https://picsum.photos/seed/prop7img1/1200/800",
      "https://picsum.photos/seed/prop7img2/1200/800",
      "https://picsum.photos/seed/prop7img3/1200/800",
    ],
  },
  {
    id: 8,
    title: "Well-Maintained 2BHK in Viman Nagar",
    price: 8500000,
    location: "Viman Nagar",
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    type: '2BHK',
    isFeatured: false,
    description: "Ready-to-move-in 2BHK apartment near Pune Airport. Perfect for those who travel frequently. Close to premier malls and eateries.",
    amenities: ["Parking", "Security", "Lift", "Balcony", "Power Backup"],
    images: [
      "https://picsum.photos/seed/prop8img1/1200/800",
      "https://picsum.photos/seed/prop8img2/1200/800",
    ],
  }
];
